openapi: 3.1.0
info:
  title: Pet Store API
  version: 1.0.0
  description: A sample Pet Store API demonstrating OpenAPI 3.1 features

servers:
  - url: http://localhost:8080/api/v1
    description: Development server

paths:
  /pets:
    get:
      operationId: listPets
      summary: List all pets
      description: Returns a list of all pets in the store
      parameters:
        - name: limit
          in: query
          description: Maximum number of pets to return
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
        - name: tag
          in: query
          description: Filter pets by tag
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      operationId: createPet
      summary: Create a pet
      description: Creates a new pet in the store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '201':
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /pets/{petId}:
    get:
      operationId: getPetById
      summary: Get a pet by ID
      description: Returns a single pet by its ID
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Pet details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      operationId: updatePet
      summary: Update a pet
      description: Updates an existing pet
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '200':
          description: Pet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      operationId: deletePet
      summary: Delete a pet
      description: Deletes a pet from the store
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Pet deleted successfully
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the pet
        name:
          type: string
          description: Name of the pet
          minLength: 1
          maxLength: 100
        tag:
          type: string
          description: Tag to categorize the pet
        status:
          $ref: '#/components/schemas/PetStatus'
        birthDate:
          type: string
          format: date-time
          description: Birth date of the pet
        owner:
          $ref: '#/components/schemas/Owner'

    NewPet:
      type: object
      required:
        - name
        - status
      properties:
        name:
          type: string
          description: Name of the pet
          minLength: 1
          maxLength: 100
        tag:
          type: string
          description: Tag to categorize the pet
        status:
          $ref: '#/components/schemas/PetStatus'
        birthDate:
          type: string
          format: date-time
          description: Birth date of the pet
        owner:
          $ref: '#/components/schemas/Owner'

    Owner:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the owner
        email:
          type: string
          format: email
          description: Email address of the owner
        phone:
          type: string
          description: Phone number of the owner

    PetStatus:
      type: string
      description: Current status of the pet
      enum:
        - available
        - pending
        - sold

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error type
        message:
          type: string
          description: Detailed error message
        code:
          type: integer
          description: Error code
